Centralize versions and use latest versions
This moves all version numbers of plugins and dependencies to
dependencyManagement and pluginManagement sections.

This still results in a compilation error on JDK 9:

  Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
  Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.antlr.v4.runtime.misc.RuleDependencyProcessor not found
	  at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1161)
	  at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
	  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	  ... 20 more